### ISSUE TITLE
The image is not inserted into the open sea

### ISSUE THREAD

**Issue by GiraffeValley** [nftdevs/NFTs-Upload-to-OpenSea#103]
the program inserts into the image something like
"blob:https://opensea.io/b2b251bf-8040-46b9-a892-6449
![Screenshot_10](https://user-images.githubusercontent.com/99540282/154809999-40096f71-e32c-4c14-84e8-e7b20ddec967.png)
30eb5d99 preview image"

**Comment by ChetanSinghJeena** [comment]
Hello, 

         This is happening because you are selecting and skipping the file one step earlier. Suppose your nft images are in B folder and B folder is inside A folder then you are selecting and skipping till B folder while you have to open B folder also. Then copy this path. I hope you have understood.

**Comment by GiraffeValley** [comment]
> Hello,
> 
> ```
>      This is happening because you are selecting and skipping the file one step earlier. Suppose your nft images are in B folder and B folder is inside A folder then you are selecting and skipping till B folder while you have to open B folder also. Then copy this path. I hope you have understood.
> ```

https://user-images.githubusercontent.com/99540282/155005385-24dee23a-e1fb-4a67-af85-3da59d5e841c.mp4

**Comment by kizaru11** [comment]
Hey did you solve this problem? Because I don't know how.
