### ISSUE TITLE
Resolved all issue but open sea changed policy 

### ISSUE THREAD

**Issue by yogesh-0586** [nftdevs/NFTs-Upload-to-OpenSea#78]
Spending whole week to resolve all issue in this code and uploaded my collection open sea but open sea changed policy for each collection only 50 item can be uploaded 

![image](https://user-images.githubusercontent.com/3482503/151438169-002ab205-5c1e-490b-aed6-c011d11a6f82.png)

**Comment by Cherokkee888** [comment]
> Spending whole week to resolve all issue in this code and uploaded my collection open sea but open sea changed policy for each collection only 50 item can be uploaded
> 
> ![image](https://user-images.githubusercontent.com/3482503/151438169-002ab205-5c1e-490b-aed6-c011d11a6f82.png)

Its just for new collection? Just tried now with my current collection and its work, collection have 1,029 NFTs and it accept to add new one.

**Comment by yogesh-0586** [comment]
> > Spending whole week to resolve all issue in this code and uploaded my collection open sea but open sea changed policy for each collection only 50 item can be uploaded
> > ![image](https://user-images.githubusercontent.com/3482503/151438169-002ab205-5c1e-490b-aed6-c011d11a6f82.png)
> 
> Its just for new collection? Just tried now with my current collection and its work, collection have 1,029 NFTs and it accept to add new one.

I'm trying to add existing collection

**Comment by yogesh-0586** [comment]
Found that open sea accept more than 50 in existing collections
